sudo: required
services:
  - docker

before_install:
  - docker build -t docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true docker-react-app npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-react-app"
  env: "Dockerreactapp-env"
  bucket_name: "elasticbeanstalk-ap-south-1-499977662464"
  bucket_path: "docker-react-app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY